### ISSUE TITLE
Corporate clash not launching

### ISSUE THREAD

**Issue by 2Epik4u** [MultiDragon/toony-linux#2]
When I  login to the game, It freezes to a black screen and this is in the logs:

```
:downloader: [000000001514D960] begin CONNECT [ https://gs.corporateclash.net:7198 ]
:downloader: Server certificate is pre-approved.
:downloader: [000000001514D960] Unable to verify identity of gs.corporateclash.net:7198, verify error code 20
```
I tried synchronizing the clock with an NTP service, and get the same issue.

I tried launching it on the offical one using wine and it worked fine. I could just use the official launcher, but it doesn't work on wayland.

**Comment by 2Epik4u** [comment]
actually, i looked at the full log and for some reason on xorg using the offical launcher it says the same thing but continues to launch the game normally.

**Comment by Wizzerinus** [comment]
Logging in with this launcher does not do anything you cannot do with an official launcher. I currently do not get any issues, so I think your OpenSSL settings are not correct.
